### ISSUE TITLE
Classifcation:    ImportError: cannot import name 'load_data' from 'sktime.utils' 

### ISSUE THREAD

**Issue by LRQ577** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#17]
Traceback (most recent call last):
  File "/home/li/NeurIPS2023-One-Fits-All-main/Classification/src/main.py", line 31, in <module>
    from datasets.data import data_factory, Normalizer
  File "/home/li/NeurIPS2023-One-Fits-All-main/Classification/src/datasets/data.py", line 12, in <module>
    from sktime.utils import load_data
ImportError: cannot import name 'load_data' from 'sktime.utils' (/home/li/anaconda3/envs/py9/lib/python3.9/site-packages/sktime/utils/__init__.py)

**Comment by PSacfc** [comment]
You need to use version sktime==0.4.1. We will update the requirements.txt later.

**Comment by doc-ycm** [comment]
`# from sktime.utils import load_data

import sktime.datasets as load_data`

**Comment by wanide** [comment]
> You need to use version sktime==0.4.1. We will update the requirements.txt later.

What should I do if the installation of sktime0.4.1 fails?
