### ISSUE TITLE
Error when running Anomaly Detection task

### ISSUE THREAD

**Issue by Maath** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#7]
I am trying to run the anomaly detection task on datasets like SMAP or MSL but I am getting the error RuntimeError: stack expects each tensor to be equal size, but got [100, 2] at entry 0 and [99, 2] at entry 29 . bellow is the Traceback  , I appreciate your help in fixing this issue and thank you very much for your hard work.

Traceback (most recent call last):
  File "run.py", line 153, in <module>
    exp.train(setting)
  File "/home/tfg/onefitsall/NeurIPS2023-One-Fits-All-main/Anomaly_Detection/exp/exp_anomaly_detection.py", line 115, in train
    test_loss = self.vali(test_data, test_loader, criterion)
  File "/home/tfg/onefitsall/NeurIPS2023-One-Fits-All-main/Anomaly_Detection/exp/exp_anomaly_detection.py", line 48, in vali
    for i, (batch_x, _) in enumerate(vali_loader):
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/opt/miniconda3/envs/onefitsall/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [100, 2] at entry 0 and [99, 2] at entry 29

**Comment by PSacfc** [comment]
I cannot reproduce the error. The number of features for SMAP and MSL datasets should be 25 and 55, respectively. It seems that the feature number mentioned ("RuntimeError: stack expects each tensor to be equal size, but got [100, 2] at entry 0 and [99, 2] at entry 29") is 2. Please verify if you have downloaded the datasets correctly (https://github.com/thuml/Anomaly-Transformer).
